/**
 * lib/teambuilder/types.ts — the data contracts for SPEC-teambuilder.md.
 *
 * The spec puts these in lib/types.ts. They live here instead, following the
 * lib/evaluator/* precedent: lib/types.ts is shared by the scraper, the calc
 * layer, both visualizations and the simulator, and adding a third project's
 * vocabulary to it makes every one of those harder to read. `Variant` itself
 * stays in lib/types.ts, since all three projects use it.
 *
 * The spec is explicit that these are not frozen: "Expect these to change
 * while the interface is being built. That is the point of building it first."
 * Phase 1 settles them. Fixtures for every shape here are generated by
 * scripts/build-teambuilder-fixtures.ts into data/fixtures/, so the interface
 * has something concrete to render before any pipeline exists.
 *
 * Browser-safe: types plus pure helpers, no Node imports.
 */
import type {Variant, StatsTable} from '../types';

// ---------------------------------------------------------------------------
// Conditions
// ---------------------------------------------------------------------------

/**
 * The teambuilder's condition vocabulary (Phase 3).
 *
 * Deliberately not lib/sim/condition.ts's `ConditionId`, which is the
 * simulator's existing set (`tailwind_A`, `trick_room`, `A_boosted_atk`, …).
 * The two differ on purpose: the simulator names mechanisms, the teambuilder
 * names states. Tailwind, Icy Wind, Trick Room, Thunder Wave and a +2 Speed
 * boost are five mechanisms and one condition, because the only thing the
 * battle depends on is whether this Pokémon moves first. Mapping between the
 * two vocabularies is Phase 5's job.
 */
export type TeambuilderConditionId =
  | 'fresh'
  | 'moves_first'
  | 'sun'
  | 'rain'
  | 'snow'
  | 'sand'
  | 'chip'
  /**
   * Extension-roadmap condition, not in the v0 five. Declared because the
   * enabler catalog has to put Intimidate, Reflect and Light Screen somewhere,
   * and mapping them onto `moves_first` because it happens to exist would be a
   * lie the interface then displays as "speed control: Reflect".
   */
  | 'phys_mitigation';

/**
 * Display name for a condition. `moves_first` is the simulator's name for the
 * state; users read it as speed control, which is what every mechanism that
 * reaches it actually is.
 */
export const CONDITION_LABELS: Record<TeambuilderConditionId, string> = {
  fresh: 'Fresh',
  moves_first: 'Speed control',
  sun: 'Sun',
  rain: 'Rain',
  snow: 'Snow',
  sand: 'Sand',
  chip: 'Chip damage',
  phys_mitigation: 'Physical mitigation',
};

/**
 * Effect categories, lifted from the team evaluator's board-control taxonomy
 * (BACKLOG item 11) so the two projects group the same effects the same way.
 *
 * `priority` is deliberately absent. Damage priority is a property of the
 * Pokémon's own matchup and is already inside its win probabilities — listing
 * it as support would count it twice.
 */
/**
 * The effect taxonomy lives in `lib/effects.ts` and is shared with the
 * evaluator (BACKLOG item 11). It used to be hand-mirrored here, which is
 * exactly the drift item 11 exists to end — the mirror had already lost the
 * rule that puts Wide and Quick Guard in the Protects row.
 *
 * Re-exported rather than re-pointed at every call site: `lib/teambuilder/`
 * is the teambuilder's vocabulary, and its screens should keep importing their
 * types from one place.
 */
import type {TeambuilderCategory as EffectCategory} from '../effects';

// Narrowed on purpose: `priority` is not a teambuilder category, and the type
// says so rather than only the runtime list. See lib/effects.ts.
export type {TeambuilderCategory as EffectCategory, DisplayGroupId} from '../effects';
export {
  CATEGORY_LABELS,
  DISPLAY_GROUPS,
  SUPPORT_CATEGORIES,
  POSITIONING_CATEGORIES,
  TEAMBUILDER_CATEGORIES,
  displayGroupFor,
  displayGroupLabel,
} from '../effects';

/** A condition reached by combining two others, e.g. rain plus moving first. */
export type CombinationConditionId = `${TeambuilderConditionId}+${TeambuilderConditionId}`;

export type AnyConditionId = TeambuilderConditionId | CombinationConditionId;

/**
 * The serializable half of a condition definition.
 *
 * SPEC-teambuilder.md defines `SimulatedCondition` and `DerivedCondition` with
 * function-valued fields (`structural_gate`, `transform`, `excluded_when`).
 * Those cannot be written to a fixture file, so the shapes are split: this
 * descriptor is what ships in JSON and what the interface renders, while the
 * registry below carries the functions. Nothing enters the registry without
 * both halves filled, which is the spec's actual requirement.
 */
export interface ConditionDescriptor {
  id: AnyConditionId;
  kind: 'simulated' | 'derived';
  /** One-line description for the interface. */
  label: string;
  /**
   * For derived conditions, what the transform reads. Derived conditions cost
   * no simulation because they truncate a battle that already ran.
   */
  derives_from?: 'final_hp_distribution' | 'cumulative_damage_curve';
}

/** A condition simulated by injecting a starting state into the battle. */
export interface SimulatedCondition extends ConditionDescriptor {
  kind: 'simulated';
  /** Cheap per-pair test: does either Pokémon read this condition at all? */
  structural_gate: (a: Variant, b: Variant, context: ConditionContext) => boolean;
  /**
   * Always simulate regardless of the outcome gate. Three cases per the spec:
   * residual damage (changes the turn clock even when damage figures hold),
   * new randomness (paralysis, sleep), and abilities that read field state.
   */
  always_simulate?: boolean;
}

/** A condition read off an already-simulated cell rather than simulated. */
export interface DerivedCondition extends ConditionDescriptor {
  kind: 'derived';
  derives_from: 'final_hp_distribution' | 'cumulative_damage_curve';
  /** Returns the adjusted p_A_wins for a given magnitude. */
  transform: (cell: MatchupCell, magnitude: number) => number;
  /**
   * Pairs where the derivation is invalid and a real simulation is needed —
   * Focus Sash, Sturdy, recovery moves, threshold berries. The resulting cell
   * is marked `excluded_fallback` so the cost of this list stays visible.
   */
  excluded_when: (a: Variant, b: Variant) => boolean;
}

export interface ConditionContext {
  regulation_id: string;
  /** Resolved legal move/ability/item lookups the gates need. */
  effects: EffectLookup;
}

/**
 * Minimal view of the shared effect table (BACKLOG item 11, lib/effects.ts,
 * lifted from the evaluator's tag tables). Declared as an interface here so
 * the gates can be written and tested before that lift happens.
 */
export interface EffectLookup {
  hasAbility(variant: Variant, ability: string): boolean;
  hasMove(variant: Variant, move: string): boolean;
  hasItem(variant: Variant, item: string): boolean;
}

// ---------------------------------------------------------------------------
// Enablers (Phase 4)
// ---------------------------------------------------------------------------

/**
 * Who an enabler can help. This scoping is what stops one Pokémon's Swords
 * Dance being credited to another, and separates setup-based mitigation from
 * screens-based mitigation.
 */
export type EnablerTarget = 'self' | 'ally_side' | 'opponent_side' | 'field';

export type MechanismClass =
  | 'switch_in_ability'
  | 'passive'
  | 'support_move'
  | 'setup_move'
  | 'status_move'
  /** Chip from a spread move's second target — free, hence action_cost 0. */
  | 'free_spread_damage';

/**
 * How fast an enabler arrives.
 *
 * 0 — free, no action required (Drought, Intimidate, Booster Energy).
 * 1 — costs an action but resolves before the opponent responds.
 * 2 — costs an action and resolves after the opponent acts.
 *
 * Tier 0 is a property of the enabler. The 1-versus-2 split is not: a
 * non-priority Tailwind user is fast against half the field and slow against
 * the other half, so it is computed per opponent. `'computed'` marks that.
 */
export type SpeedTier = 0 | 1 | 2;
export type SpeedTierSpec = SpeedTier | 'computed';

export interface Enabler {
  condition: AnyConditionId;
  /** Namespaced mechanism, e.g. "move:Bulk Up", "ability:Drizzle". */
  mechanism: string;
  mechanism_class: MechanismClass;
  /** Which effect bucket this belongs to, for grouping across candidates. */
  category: EffectCategory;
  target: EnablerTarget;
  /** Actions the enabler costs. 0 for passives and free spread chip. */
  action_cost: number;
  speed_tier: SpeedTierSpec;
  /**
   * Share of the metagame by usage this enabler resolves against before the
   * opponent can act. Only meaningful when `speed_tier` is 'computed' — a
   * non-priority Tailwind user is fast against some of the field and slow
   * against the rest, and the single number is what a reader can actually use.
   * Tier 0 enablers are 1 by definition; tier 2 are 0.
   */
  first_share?: number;
  /**
   * Derived-condition enablers carry an amount rather than a yes-or-no fact.
   * `'calc'` means the amount is computed at scoring time by running the
   * damage calculator for this mechanism against the opponent in question.
   */
  magnitude?: 'calc' | number;
}

/** One variant's enabler records. One per mechanism-and-condition pair. */
export interface EnablerRecord {
  variant_id: string;
  human_id: string;
  enablers: Enabler[];
}

// ---------------------------------------------------------------------------
// Matrix (Phase 5)
// ---------------------------------------------------------------------------

/**
 * How a cell came to hold its value. Every pair-and-condition combination has
 * a row — a query never returns null or unavailable.
 */
export type CellStatus = 'simulated' | 'inherited' | 'excluded_fallback';

export interface MatchupCell {
  variant_A_id: string;
  variant_B_id: string;
  condition: AnyConditionId;
  p_A_wins: number;
  mean_turns: number;
  /**
   * Sorted quantiles of the winner's remaining HP as a fraction of maximum,
   * one array per side's wins. Stored instead of a mean because a mean
   * discards exactly what makes chip a lookup and drives the positioning
   * analysis.
   */
  hp_quantiles_A_won: number[];
  hp_quantiles_B_won: number[];
  /**
   * Each side's remaining HP when the other fainted. Costs nothing to collect
   * now and is what a later mitigation extrapolation would need
   * (BACKLOG item 13).
   */
  hp_at_opponent_faint_A: number;
  hp_at_opponent_faint_B: number;
  /**
   * Per-turn cumulative damage, core-against-core only. Presence is what
   * gates the free-boost derivation (BACKLOG item 12).
   */
  cumulative_damage_A?: number[];
  cumulative_damage_B?: number[];
  status: CellStatus;
  /** Set when status is `inherited`: the condition the value came from. */
  inherited_from?: AnyConditionId;
  /** True while a custom set's real simulation is still running (Phase 6b). */
  provisional?: boolean;
  regulation_id: string;
  policy_version: string;
  calc_version: string;
  sim_engine_version: string;
}

// ---------------------------------------------------------------------------
// Positioning (Phase 6)
// ---------------------------------------------------------------------------

export interface CostlyEntry {
  opponent: string;
  species: string;
  /** Entry cost as a fraction of max HP, from the opponent's best move. */
  cost: number;
  /** Share of the full-health matchup spread retained after paying it. */
  spread_retained: number;
}

export interface PositioningTool {
  /** Namespaced, e.g. "move:U-turn", "ability:Intimidate". */
  tool: string;
  effect:
    | 'entry_cost_to_zero'
    | 'physical_two_thirds'
    | 'relevant_two_thirds'
    | 'all_three_quarters'
    | 'weather_factor';
  speed_tier: SpeedTierSpec;
}

export interface PositioningProfile {
  variant_id: string;
  /** Usage-weighted matchup spread retained after paying entry costs. */
  switch_in_score: number;
  /** Share of the field P can enter on while keeping ≥80% of its spread. */
  entry_coverage: number;
  /** Across that share, how many opponents P is actually favoured against. */
  conversion: number;
  costly_entries: CostlyEntry[];
  tools_provided: PositioningTool[];
}

// ---------------------------------------------------------------------------
// Scoring (Phase 7)
// ---------------------------------------------------------------------------

export interface SuppliedCondition {
  condition: AnyConditionId;
  /** Bucket for grouping, so the same category sits in the same place on every row. */
  category: EffectCategory;
  enablers: Array<{
    member: string;
    mechanism: string;
    speed_tier: SpeedTierSpec;
    /** See Enabler.first_share — the share of the field this beats to the punch. */
    first_share?: number;
  }>;
  /**
   * Teammate win-rate gain attributable to this condition alone, in percentage
   * points. Summing these across conditions over-counts when two conditions
   * help the same matchup, so `Candidate.support_delta` is computed jointly
   * rather than as a sum of these.
   */
  delta?: number;
}

export interface WorstMatchup {
  variant_id: string;
  species: string;
  weight: number;
  p_exposed: number;
  best_answer: {member: string; condition: AnyConditionId; p: number};
}

/** Tally of mechanism classes and speed tiers across a team's conditions. */
export interface SetupProfile {
  switch_in_ability: number;
  passive: number;
  support_move: number;
  setup_move: number;
  status_move: number;
  tier_0: number;
  tier_1: number;
  tier_2: number;
}

export interface TeamPositioningSummary {
  member_entry_coverage: Array<{member: string; coverage: number}>;
  unreachable_opponents: Array<{species: string; weight: number}>;
}

export interface TeamScore {
  members: string[];
  /** With every supplied condition available. A ceiling, not an expectation. */
  score_ceiling: number;
  /** The same computation with conditions reduced to `fresh` and chip zeroed. */
  score_floor: number;
  /** (ceiling − floor) / ceiling. How much setup the team is asking for. */
  condition_reliance: number;
  conditions_supplied: SuppliedCondition[];
  setup_profile: SetupProfile;
  /**
   * Reported alongside the score, never folded into it: a single number would
   * hide which of matchups, enablers or positioning a weak team is failing.
   */
  positioning: TeamPositioningSummary;
  /** Highest-weight matchups scoring below 0.4. */
  worst_matchups: WorstMatchup[];
  /** Count of metagame variants with at least one answer above 0.5. */
  coverage_breadth: number;
  /** Leave-one-out score delta — does the sixth slot do anything? */
  member_contributions: Array<{variant_id: string; marginal_score: number}>;
}

// ---------------------------------------------------------------------------
// Search (Phase 8)
// ---------------------------------------------------------------------------

/**
 * A candidate for the next team slot.
 *
 * The three surfacing rules are independent on purpose. A redirection user
 * with no winning matchups and no conditions still has to appear, which
 * `marginal_score` alone would never show.
 */
/**
 * One matchup this candidate swings for a teammate.
 *
 * The number on a tile says how much changed; this says what changed, which is
 * what a reader actually checks the number against. "Tailwind moves Basculegion
 * from 41% to 78% against Floette" is inspectable in a way that "+4.6%" is not.
 */
export interface ValueSwing {
  /** The team member whose matchup improves. Absent on self-swings. */
  teammate?: string;
  teammate_species?: string;
  opponent: string;
  opponent_species: string;
  /** Usage weight of the opponent, for ordering by impact. */
  weight: number;
  before: number;
  after: number;
  /** The condition responsible — support swings only. */
  condition?: AnyConditionId;
  /** The mechanism responsible, e.g. "move:Tailwind". */
  mechanism?: string;
}

export interface Candidate {
  variant_id: string;
  human_id: string;
  species: string;
  set_label: string;
  is_mega: boolean;
  /**
   * (a) Matchup coverage, in percentage points of metagame-weighted team score:
   * score(T + this) − score(T). Incremental by construction — a Pokémon that
   * beats Garchomp 90% of the time adds nothing if a teammate already beats it
   * 88%, because `p_exposed` takes the team's best answer.
   */
  marginal_score: number;
  /**
   * (b) Support, in the same unit: how much this member raises its *teammates'*
   * metagame-weighted win rate by supplying conditions they convert on. A
   * Tailwind user that lets a slow attacker move first scores here, not under
   * matchup coverage, because the gain belongs to the teammate.
   */
  support_delta: number;
  /** The conditions behind `support_delta`, for the pills on the card. */
  conditions_added: SuppliedCondition[];
  /**
   * The biggest matchups this member's support swings for teammates, most
   * impactful first. Not exhaustive — the top few are what makes the delta
   * checkable.
   */
  support_swings: ValueSwing[];
  /**
   * (c) Positioning, in the same unit: how much this member raises teammates'
   * win rate by letting them reach their good matchups — pivots, redirection,
   * entry-cost reduction.
   *
   * Provisional. Expressing positioning as a win-rate delta makes it
   * comparable with the other two, but whether that is the right display is
   * open until the Phase 6 logic is real; `opponents_unlocked` is the concrete
   * detail behind it.
   */
  positioning_delta: number;
  /**
   * Opponents a teammate can now safely enter against that it could not
   * before. The legible version of `positioning_delta`.
   */
  opponents_unlocked: Array<{species: string; weight: number; helps: string}>;
  /** The biggest entry swings this member creates for teammates. */
  positioning_swings: ValueSwing[];
  /**
   * Effect categories this member's positioning tools fall under. Separate
   * from `conditions_added` because a pivot or a redirector supplies no
   * condition — it changes who can reach a fight, not what the fight is.
   */
  positioning_categories: EffectCategory[];
  /** Entry coverage this candidate has on its own. */
  entry_coverage: number;
  /** Opponents this candidate answers that the current team does not. */
  patches: WorstMatchup[];
  /**
   * Every preset set for this species and item bucket. The Build screen opens
   * the editor on whichever one the candidate row represents and offers the
   * rest alongside it.
   */
  sets?: PresetSet[];
  /** True until a custom set's simulations land (Phase 6b). */
  provisional?: boolean;
  /** Set when the candidate came from the custom-set editor rather than usage. */
  source?: 'preset' | 'custom';
}

/** One named set for a species — what the preset picker lists. */
export interface PresetSet {
  variant_id: string;
  human_id: string;
  set_label: string;
  item: string | null;
  ability: string;
  nature: string;
  sps: Partial<StatsTable>;
  moves: string[];
  /** Share of this species' usage running this set. */
  usage_share: number;
  tier?: 'core' | 'extended';
}

// ---------------------------------------------------------------------------
// Custom sets (Phase 6b)
// ---------------------------------------------------------------------------

/**
 * A user-defined set in the editor, before it becomes a variant.
 *
 * Validated against lib/format-rules.ts and the SP budget as the user types,
 * so an illegal set is rejected in the editor rather than after a job is
 * queued.
 */
export interface CustomSetDraft {
  species: string;
  ability: string;
  item: string | null;
  nature: string;
  sps: Partial<StatsTable>;
  moves: string[];
  /** Set once the draft is legal — the content id it will be stored under. */
  cid?: string;
  /** Preset this draft was warm-started from, when it began as an edit. */
  warm_start_from?: string;
  validation_errors: string[];
}
